#!/usr/bin/env python3
"""Sync Service Lasso managed workflow registry entries into Dagu YAML files."""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any

MANAGED_BY = "service-lasso"
MANAGED_MARKER = "managedBy: service-lasso"
DEFAULT_ACTION_API = "http://127.0.0.1:17883"
DEFAULT_ACTION_RUNNER = "scripts/run-service-lasso-action.py"


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


def read_registry(source: str) -> dict[str, Any]:
    if re.match(r"^https?://", source):
      with urllib.request.urlopen(source, timeout=30) as response:
          return json.loads(response.read().decode("utf-8"))

    return json.loads(Path(source).read_text(encoding="utf-8"))


def registry_entries(registry: Any) -> list[dict[str, Any]]:
    if isinstance(registry, list):
        entries = registry
    elif isinstance(registry, dict):
        entries = registry.get("workflows", registry.get("items", []))
    else:
        raise ValueError("registry must be a JSON object or array")

    if not isinstance(entries, list):
        raise ValueError("registry workflows/items must be a list")

    return [entry for entry in entries if isinstance(entry, dict)]


def stable_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip("-._")
    return name or "workflow"


def safe_segment(value: str) -> str:
    return stable_name(value).replace("..", ".")


def quote_yaml(value: Any) -> str:
    if value is None:
        return '""'
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    return json.dumps(text)


def step_parent_action_id(entry: dict[str, Any], step: dict[str, Any]) -> str:
    return str(step.get("parentActionId") or entry.get("actionId") or "")


def step_payload_ref(step: dict[str, Any]) -> str | None:
    if step.get("payloadRef") is not None:
        return str(step["payloadRef"])
    legacy = step.get("inputRef")
    if isinstance(legacy, dict) and legacy.get("id"):
        return str(legacy["id"])
    if legacy is not None:
        return str(legacy)
    return None


def step_inline_payload(step: dict[str, Any]) -> dict[str, Any] | None:
    if step.get("payload") is not None:
        return step["payload"]
    if step.get("inputs") is not None:
        return step["inputs"]
    return None


def action_url(action_api_url: str, step: dict[str, Any]) -> str:
    base = action_api_url.rstrip("/")
    service_id = urllib.request.pathname2url(str(step["serviceId"]))
    action_id = urllib.request.pathname2url(str(step["actionId"]))
    return f"{base}/api/services/{service_id}/actions/{action_id}/runs"


def render_workflow(entry: dict[str, Any], action_api_url: str, action_runner: str) -> str:
    workflow_id = str(entry["id"])
    service_id = str(entry["serviceId"])
    action_id = str(entry.get("actionId", ""))
    schedule_id = str(entry.get("scheduleId", ""))
    checksum = str(entry.get("checksum", ""))
    cron = entry.get("cron")
    steps = entry.get("steps") or []

    lines = [
        "# Generated by lasso-dagu. Do not edit by hand.",
        f"name: {quote_yaml(stable_name(workflow_id))}",
        f"description: {quote_yaml('Service Lasso managed workflow ' + workflow_id)}",
    ]
    if cron:
        lines.append(f"schedule: {quote_yaml(cron)}")
    lines.extend(
        [
            "",
            "x-service-lasso:",
            f"  managedBy: {MANAGED_BY}",
            f"  workflowId: {quote_yaml(workflow_id)}",
            f"  serviceId: {quote_yaml(service_id)}",
            f"  actionId: {quote_yaml(action_id)}",
            f"  scheduleId: {quote_yaml(schedule_id)}",
            f"  checksum: {quote_yaml(checksum)}",
            "  driftPolicy: overwrite",
            "",
            "steps:",
        ]
    )

    for step in steps:
        parent_action_id = step_parent_action_id(entry, step)
        payload_ref = step_payload_ref(step)
        inline_payload = step_inline_payload(step)
        lines.extend(
            [
                f"  - name: {quote_yaml(stable_name(str(step['id'])))}",
                "    command: python",
                "    args:",
                f"      - {quote_yaml(action_runner)}",
                "      - --url",
                f"      - {quote_yaml(action_url(action_api_url, step))}",
                "      - --workflow-id",
                f"      - {quote_yaml(workflow_id)}",
                "      - --schedule-id",
                f"      - {quote_yaml(schedule_id)}",
                "      - --step-id",
                f"      - {quote_yaml(str(step['id']))}",
                "      - --service-id",
                f"      - {quote_yaml(str(step['serviceId']))}",
                "      - --action-id",
                f"      - {quote_yaml(str(step['actionId']))}",
                "      - --parent-action-id",
                f"      - {quote_yaml(parent_action_id)}",
            ]
        )
        if payload_ref is not None:
            lines.extend(["      - --payload-ref", f"      - {quote_yaml(payload_ref)}"])
        if inline_payload is not None:
            lines.extend(
                [
                    "      - --inline-payload",
                    f"      - {quote_yaml(json.dumps(inline_payload, separators=(',', ':'), sort_keys=True))}",
                ]
            )

    return "\n".join(lines) + "\n"


def validate_entry(entry: dict[str, Any]) -> None:
    required = ["id", "serviceId", "actionId", "scheduleId", "steps"]
    missing = [field for field in required if not entry.get(field)]
    if missing:
        raise ValueError(f"workflow entry missing required fields: {', '.join(missing)}")

    if not isinstance(entry["steps"], list) or not entry["steps"]:
        raise ValueError(f"workflow {entry['id']} must include at least one step")

    for step in entry["steps"]:
        if not isinstance(step, dict):
            raise ValueError(f"workflow {entry['id']} contains a non-object step")
        for field in ["id", "serviceId", "actionId"]:
            if not step.get(field):
                raise ValueError(f"workflow {entry['id']} step missing {field}")
        if step.get("type", "service-lasso-action") != "service-lasso-action":
            raise ValueError(f"workflow {entry['id']} step {step['id']} has unsupported type")
        payload_ref = step_payload_ref(step)
        if payload_ref is not None and not re.match(r"^[A-Za-z0-9_.-]+$", payload_ref):
            raise ValueError(f"workflow {entry['id']} step {step['id']} has invalid payloadRef")
        inline_payload = step_inline_payload(step)
        if inline_payload is not None and not isinstance(inline_payload, dict):
            raise ValueError(f"workflow {entry['id']} step {step['id']} payload must be a JSON object")


def managed_path(output_dir: Path, entry: dict[str, Any]) -> Path:
    service_id = safe_segment(str(entry["serviceId"]))
    workflow_id = stable_name(str(entry["id"]))
    return output_dir / service_id / f"{workflow_id}.yaml"


def prune_stale(output_dir: Path, expected: set[Path]) -> list[Path]:
    removed: list[Path] = []
    if not output_dir.exists():
        return removed

    for path in output_dir.rglob("*.yaml"):
        if path in expected:
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if MANAGED_MARKER in text:
            path.unlink()
            removed.append(path)

    return removed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", required=True, help="Registry JSON file or URL.")
    parser.add_argument("--output-dir", required=True, help="Generated Dagu workflow directory.")
    parser.add_argument("--action-api-url", default=DEFAULT_ACTION_API, help="Service Lasso action API base URL.")
    parser.add_argument("--action-runner", default=DEFAULT_ACTION_RUNNER, help="Generated Dagu task runner script path.")
    parser.add_argument("--prune-stale", action="store_true", help="Remove stale generated workflows under output-dir.")
    args = parser.parse_args()

    try:
        registry = read_registry(args.registry)
        entries = registry_entries(registry)
        output_dir = Path(args.output_dir)
        expected_paths: set[Path] = set()
        written: list[Path] = []

        for entry in entries:
            if entry.get("managedBy", MANAGED_BY) != MANAGED_BY:
                continue
            if entry.get("enabled", True) is False:
                continue
            validate_entry(entry)
            path = managed_path(output_dir, entry)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render_workflow(entry, args.action_api_url, args.action_runner), encoding="utf-8")
            expected_paths.add(path)
            written.append(path)

        removed = prune_stale(output_dir, expected_paths) if args.prune_stale else []
        print(
            json.dumps(
                {
                    "ok": True,
                    "written": [str(path) for path in written],
                    "removed": [str(path) for path in removed],
                    "driftPolicy": "overwrite",
                    "disabledPolicy": "omit-and-prune",
                },
                indent=2,
            )
        )
        return 0
    except Exception as exc:  # noqa: BLE001 - CLI reports concise operator-facing failures.
        return fail(str(exc))


if __name__ == "__main__":
    raise SystemExit(main())
